# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Work\stbxengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Work\stbxengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Work\stbxengine\CMakeFiles D:\Work\stbxengine\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Work\stbxengine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sengine

# Build rule for target.
sengine: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sengine
.PHONY : sengine

# fast build rule for target.
sengine/fast:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/build
.PHONY : sengine/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) -f extlib\sfml\src\SFML\System\CMakeFiles\sfml-system.dir\build.make extlib/sfml/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-main

# Build rule for target.
sfml-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sfml-main
.PHONY : sfml-main

# fast build rule for target.
sfml-main/fast:
	$(MAKE) -f extlib\sfml\src\SFML\Main\CMakeFiles\sfml-main.dir\build.make extlib/sfml/src/SFML/Main/CMakeFiles/sfml-main.dir/build
.PHONY : sfml-main/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) -f extlib\sfml\src\SFML\Window\CMakeFiles\sfml-window.dir\build.make extlib/sfml/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) -f extlib\sfml\src\SFML\Network\CMakeFiles\sfml-network.dir\build.make extlib/sfml/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) -f extlib\sfml\src\SFML\Graphics\CMakeFiles\sfml-graphics.dir\build.make extlib/sfml/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) -f extlib\sfml\src\SFML\Audio\CMakeFiles\sfml-audio.dir\build.make extlib/sfml/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

extlib/pugixml/src/pugixml.obj: extlib/pugixml/src/pugixml.cpp.obj

.PHONY : extlib/pugixml/src/pugixml.obj

# target to build an object file
extlib/pugixml/src/pugixml.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/extlib/pugixml/src/pugixml.cpp.obj
.PHONY : extlib/pugixml/src/pugixml.cpp.obj

extlib/pugixml/src/pugixml.i: extlib/pugixml/src/pugixml.cpp.i

.PHONY : extlib/pugixml/src/pugixml.i

# target to preprocess a source file
extlib/pugixml/src/pugixml.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/extlib/pugixml/src/pugixml.cpp.i
.PHONY : extlib/pugixml/src/pugixml.cpp.i

extlib/pugixml/src/pugixml.s: extlib/pugixml/src/pugixml.cpp.s

.PHONY : extlib/pugixml/src/pugixml.s

# target to generate assembly for a file
extlib/pugixml/src/pugixml.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/extlib/pugixml/src/pugixml.cpp.s
.PHONY : extlib/pugixml/src/pugixml.cpp.s

src/Commands.obj: src/Commands.cpp.obj

.PHONY : src/Commands.obj

# target to build an object file
src/Commands.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Commands.cpp.obj
.PHONY : src/Commands.cpp.obj

src/Commands.i: src/Commands.cpp.i

.PHONY : src/Commands.i

# target to preprocess a source file
src/Commands.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Commands.cpp.i
.PHONY : src/Commands.cpp.i

src/Commands.s: src/Commands.cpp.s

.PHONY : src/Commands.s

# target to generate assembly for a file
src/Commands.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Commands.cpp.s
.PHONY : src/Commands.cpp.s

src/Console.obj: src/Console.cpp.obj

.PHONY : src/Console.obj

# target to build an object file
src/Console.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Console.cpp.obj
.PHONY : src/Console.cpp.obj

src/Console.i: src/Console.cpp.i

.PHONY : src/Console.i

# target to preprocess a source file
src/Console.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Console.cpp.i
.PHONY : src/Console.cpp.i

src/Console.s: src/Console.cpp.s

.PHONY : src/Console.s

# target to generate assembly for a file
src/Console.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Console.cpp.s
.PHONY : src/Console.cpp.s

src/Control.obj: src/Control.cpp.obj

.PHONY : src/Control.obj

# target to build an object file
src/Control.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Control.cpp.obj
.PHONY : src/Control.cpp.obj

src/Control.i: src/Control.cpp.i

.PHONY : src/Control.i

# target to preprocess a source file
src/Control.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Control.cpp.i
.PHONY : src/Control.cpp.i

src/Control.s: src/Control.cpp.s

.PHONY : src/Control.s

# target to generate assembly for a file
src/Control.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Control.cpp.s
.PHONY : src/Control.cpp.s

src/Engine.obj: src/Engine.cpp.obj

.PHONY : src/Engine.obj

# target to build an object file
src/Engine.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Engine.cpp.obj
.PHONY : src/Engine.cpp.obj

src/Engine.i: src/Engine.cpp.i

.PHONY : src/Engine.i

# target to preprocess a source file
src/Engine.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Engine.cpp.i
.PHONY : src/Engine.cpp.i

src/Engine.s: src/Engine.cpp.s

.PHONY : src/Engine.s

# target to generate assembly for a file
src/Engine.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Engine.cpp.s
.PHONY : src/Engine.cpp.s

src/GUI.obj: src/GUI.cpp.obj

.PHONY : src/GUI.obj

# target to build an object file
src/GUI.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUI.cpp.obj
.PHONY : src/GUI.cpp.obj

src/GUI.i: src/GUI.cpp.i

.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s

.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/GUIButton.obj: src/GUIButton.cpp.obj

.PHONY : src/GUIButton.obj

# target to build an object file
src/GUIButton.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIButton.cpp.obj
.PHONY : src/GUIButton.cpp.obj

src/GUIButton.i: src/GUIButton.cpp.i

.PHONY : src/GUIButton.i

# target to preprocess a source file
src/GUIButton.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIButton.cpp.i
.PHONY : src/GUIButton.cpp.i

src/GUIButton.s: src/GUIButton.cpp.s

.PHONY : src/GUIButton.s

# target to generate assembly for a file
src/GUIButton.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIButton.cpp.s
.PHONY : src/GUIButton.cpp.s

src/GUIElement.obj: src/GUIElement.cpp.obj

.PHONY : src/GUIElement.obj

# target to build an object file
src/GUIElement.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIElement.cpp.obj
.PHONY : src/GUIElement.cpp.obj

src/GUIElement.i: src/GUIElement.cpp.i

.PHONY : src/GUIElement.i

# target to preprocess a source file
src/GUIElement.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIElement.cpp.i
.PHONY : src/GUIElement.cpp.i

src/GUIElement.s: src/GUIElement.cpp.s

.PHONY : src/GUIElement.s

# target to generate assembly for a file
src/GUIElement.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIElement.cpp.s
.PHONY : src/GUIElement.cpp.s

src/GUIEntity.obj: src/GUIEntity.cpp.obj

.PHONY : src/GUIEntity.obj

# target to build an object file
src/GUIEntity.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIEntity.cpp.obj
.PHONY : src/GUIEntity.cpp.obj

src/GUIEntity.i: src/GUIEntity.cpp.i

.PHONY : src/GUIEntity.i

# target to preprocess a source file
src/GUIEntity.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIEntity.cpp.i
.PHONY : src/GUIEntity.cpp.i

src/GUIEntity.s: src/GUIEntity.cpp.s

.PHONY : src/GUIEntity.s

# target to generate assembly for a file
src/GUIEntity.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIEntity.cpp.s
.PHONY : src/GUIEntity.cpp.s

src/GUIPanel.obj: src/GUIPanel.cpp.obj

.PHONY : src/GUIPanel.obj

# target to build an object file
src/GUIPanel.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIPanel.cpp.obj
.PHONY : src/GUIPanel.cpp.obj

src/GUIPanel.i: src/GUIPanel.cpp.i

.PHONY : src/GUIPanel.i

# target to preprocess a source file
src/GUIPanel.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIPanel.cpp.i
.PHONY : src/GUIPanel.cpp.i

src/GUIPanel.s: src/GUIPanel.cpp.s

.PHONY : src/GUIPanel.s

# target to generate assembly for a file
src/GUIPanel.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/GUIPanel.cpp.s
.PHONY : src/GUIPanel.cpp.s

src/Keybinds.obj: src/Keybinds.cpp.obj

.PHONY : src/Keybinds.obj

# target to build an object file
src/Keybinds.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Keybinds.cpp.obj
.PHONY : src/Keybinds.cpp.obj

src/Keybinds.i: src/Keybinds.cpp.i

.PHONY : src/Keybinds.i

# target to preprocess a source file
src/Keybinds.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Keybinds.cpp.i
.PHONY : src/Keybinds.cpp.i

src/Keybinds.s: src/Keybinds.cpp.s

.PHONY : src/Keybinds.s

# target to generate assembly for a file
src/Keybinds.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Keybinds.cpp.s
.PHONY : src/Keybinds.cpp.s

src/Menu.obj: src/Menu.cpp.obj

.PHONY : src/Menu.obj

# target to build an object file
src/Menu.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Menu.cpp.obj
.PHONY : src/Menu.cpp.obj

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/MenuItem.obj: src/MenuItem.cpp.obj

.PHONY : src/MenuItem.obj

# target to build an object file
src/MenuItem.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/MenuItem.cpp.obj
.PHONY : src/MenuItem.cpp.obj

src/MenuItem.i: src/MenuItem.cpp.i

.PHONY : src/MenuItem.i

# target to preprocess a source file
src/MenuItem.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/MenuItem.cpp.i
.PHONY : src/MenuItem.cpp.i

src/MenuItem.s: src/MenuItem.cpp.s

.PHONY : src/MenuItem.s

# target to generate assembly for a file
src/MenuItem.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/MenuItem.cpp.s
.PHONY : src/MenuItem.cpp.s

src/Resolver.obj: src/Resolver.cpp.obj

.PHONY : src/Resolver.obj

# target to build an object file
src/Resolver.cpp.obj:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Resolver.cpp.obj
.PHONY : src/Resolver.cpp.obj

src/Resolver.i: src/Resolver.cpp.i

.PHONY : src/Resolver.i

# target to preprocess a source file
src/Resolver.cpp.i:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Resolver.cpp.i
.PHONY : src/Resolver.cpp.i

src/Resolver.s: src/Resolver.cpp.s

.PHONY : src/Resolver.s

# target to generate assembly for a file
src/Resolver.cpp.s:
	$(MAKE) -f CMakeFiles\sengine.dir\build.make CMakeFiles/sengine.dir/src/Resolver.cpp.s
.PHONY : src/Resolver.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... sengine
	@echo ... edit_cache
	@echo ... install
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... install/strip
	@echo ... install/local
	@echo ... sfml-system
	@echo ... sfml-main
	@echo ... sfml-window
	@echo ... sfml-network
	@echo ... sfml-graphics
	@echo ... sfml-audio
	@echo ... extlib/pugixml/src/pugixml.obj
	@echo ... extlib/pugixml/src/pugixml.i
	@echo ... extlib/pugixml/src/pugixml.s
	@echo ... src/Commands.obj
	@echo ... src/Commands.i
	@echo ... src/Commands.s
	@echo ... src/Console.obj
	@echo ... src/Console.i
	@echo ... src/Console.s
	@echo ... src/Control.obj
	@echo ... src/Control.i
	@echo ... src/Control.s
	@echo ... src/Engine.obj
	@echo ... src/Engine.i
	@echo ... src/Engine.s
	@echo ... src/GUI.obj
	@echo ... src/GUI.i
	@echo ... src/GUI.s
	@echo ... src/GUIButton.obj
	@echo ... src/GUIButton.i
	@echo ... src/GUIButton.s
	@echo ... src/GUIElement.obj
	@echo ... src/GUIElement.i
	@echo ... src/GUIElement.s
	@echo ... src/GUIEntity.obj
	@echo ... src/GUIEntity.i
	@echo ... src/GUIEntity.s
	@echo ... src/GUIPanel.obj
	@echo ... src/GUIPanel.i
	@echo ... src/GUIPanel.s
	@echo ... src/Keybinds.obj
	@echo ... src/Keybinds.i
	@echo ... src/Keybinds.s
	@echo ... src/Menu.obj
	@echo ... src/Menu.i
	@echo ... src/Menu.s
	@echo ... src/MenuItem.obj
	@echo ... src/MenuItem.i
	@echo ... src/MenuItem.s
	@echo ... src/Resolver.obj
	@echo ... src/Resolver.i
	@echo ... src/Resolver.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

